### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.Kestrel.Linux#11]
Collect some stats to know the implementation behaves.
Stats can be printed out on stop to the console.
Enable print-out via a TransportOption.

**Comment by omajid** [comment]
What sorts of stats might be useful? Which ones can we actually get? Do we have any way to find out, for example, how often the pipes are being read from or written to?

**Comment by tmds** [comment]
- time spent between first poll event and doCloseAccept

in this timespan, and total:
- number of epoll waits
- number accept, read, write events

in total:
- number of successful accepts
- number of sockets that detect writable events
- number of eagains in receive
- histogram of numevents returned by epoll wait
- histogram of number iovects used for receive, send

These stats are not intended for the end-user but for understanding better how the implementation behaves so we can fine-tune magical constants and update behavior.
